name: encodeVCF

on:
  push:
    branches:
      - main

jobs:
  embed_encoded_contact_media:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Insert photo into vCard
        run: |
          PHOTO=$(base64 contact/profile.jpg)
          awk -v photo="$PHOTO" '{gsub("%INSERT_PHOTO%", photo)}1' contact/contact.vcf > contact/contact.vcf
          cat contact/contact.vcf

      - name: Insert pronunciation into vCard
        run: |
          PRONUNCIATION=$(base64 contact/profile.jpg)
          awk -v pronunciation="$PRONUNCIATION" '{gsub("%INSERT_PHOTO%", pronunciation)}1' contact/contact.vcf > contact/contact.vcf
          cat contact/contact.vcf

      - name: Commit and push changes
        run: |
          git config user.email "mauriciom.curiel@gmail.com"
          git config user.name "Mauricio Curiel"
          echo "finished configuring git"

          git status
          git add contact/contact.vcf
          git commit -m "pushing production contact card"
          echo "committed changes"
          echo "attempting to push changes"
          git push -f origin production
